package entity;
// Generated Nov 10, 2021 5:11:14 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Admin generated by hbm2java
 */
public class Admin  implements java.io.Serializable {


     private Integer idAdmin;
     private String fullName;
     private String username;
     private String password;
     private Date birthday;
     private String gmail;
     private Integer sdt;
     private Set movieAdmins = new HashSet(0);

    public Admin() {
    }

    public Admin(String username, String password) {
        this.username = username;
        this.password = password;
    }

    
    public Admin(String fullName, String username, String password, Date birthday, String gmail, Integer sdt, Set movieAdmins) {
       this.fullName = fullName;
       this.username = username;
       this.password = password;
       this.birthday = birthday;
       this.gmail = gmail;
       this.sdt = sdt;
       this.movieAdmins = movieAdmins;
    }
   
    public Integer getIdAdmin() {
        return this.idAdmin;
    }
    
    public void setIdAdmin(Integer idAdmin) {
        this.idAdmin = idAdmin;
    }
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
    public String getGmail() {
        return this.gmail;
    }
    
    public void setGmail(String gmail) {
        this.gmail = gmail;
    }
    public Integer getSdt() {
        return this.sdt;
    }
    
    public void setSdt(Integer sdt) {
        this.sdt = sdt;
    }
    public Set getMovieAdmins() {
        return this.movieAdmins;
    }
    
    public void setMovieAdmins(Set movieAdmins) {
        this.movieAdmins = movieAdmins;
    }




}


